Fixed Command Injection vulnerability for android app command
418sec/logkitty pull request #2
Opened 2020-03-27 21:05 UTC by MirceaConstantin

2020-03-31 13:47 UTC, 69 commented
Still vulnerable with the following payload:
```bash
logkitty android app $'test\' "$(touch HACKED)" \''
```

2020-04-03 11:51 UTC, toufik-airane requested changes
Dear @MirceaConstantin,

The fix doesn't fully mitigate the potential command injection.
Thank you for your contribution.

2020-04-03 11:51 UTC, toufik-airane commented on src/android/adb.ts
> +  if (applicationId.match(/[;&|]/)) throw new CodeError(ERR_ANDROID_CANNOT_GET_APP_PID, ERR_ANDROID_UNPROCESSABLE_PID)
The regexp doesn't fully mitigate the potential command injection.

2020-04-03 18:03 UTC, huntr-helper commented
Sorry @MirceaConstantin, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request! We appreciate your effort and look forward to reviewing more of your fixes in the future! :hammer: :sunglasses:

2020-04-03 18:03 UTC, closed without merging